from enum import Enum

class Zone(str, Enum):
    CZE = "CZE"
    DE_LU = "DE-LU"
    AT = "AT"
    CH = "CH"
    FR = "FR"
    NL = "NL"
    BE = "BE"
    DK1 = "DK1"
    DK2 = "DK2"
    SE1 = "SE1"
    NO1 = "NO1"
    FI = "FI"
    PL = "PL"
    IT_NORD = "IT-NORD"
    IT_CNOR = "IT-CNOR"
    IT_CSUD = "IT-CSUD"
    IT_SUD = "IT-SUD"
    IT_SARD = "IT-SARD"
    IT_SICI = "IT-SICI"
    ES = "ES"
    PT = "PT"
    HU = "HU"
    SK = "SK"
    SI = "SI"
    HR = "HR"